// <auto-generated />
using System;
using Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260201122232_BrewEnttity_Name_Changes")]
    partial class BrewEnttity_Name_Changes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Api.Database.Entities.BrewEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BrewAddedWeight")
                        .HasColumnType("REAL");

                    b.Property<int?>("BrewAddedWeightTasteScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrewTasteScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrewTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrewType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("BrewWeight")
                        .HasColumnType("REAL");

                    b.Property<int>("CoffeeBagId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CoffeeDose")
                        .HasColumnType("REAL");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<double?>("GrindSize")
                        .HasColumnType("REAL");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeBagId");

                    b.HasIndex("UserId");

                    b.ToTable("Brews");
                });

            modelBuilder.Entity("Api.Database.Entities.CoffeeBagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Emptied")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavourNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Opened")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoastStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Roaster")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CoffeeBags");
                });

            modelBuilder.Entity("Api.Database.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Api.Database.Entities.BrewEntity", b =>
                {
                    b.HasOne("Api.Database.Entities.CoffeeBagEntity", "CoffeeBag")
                        .WithMany("Brews")
                        .HasForeignKey("CoffeeBagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.UserEntity", "User")
                        .WithMany("Brews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoffeeBag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Database.Entities.CoffeeBagEntity", b =>
                {
                    b.HasOne("Api.Database.Entities.UserEntity", "User")
                        .WithMany("CoffeeBags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Database.Entities.CoffeeBagEntity", b =>
                {
                    b.Navigation("Brews");
                });

            modelBuilder.Entity("Api.Database.Entities.UserEntity", b =>
                {
                    b.Navigation("Brews");

                    b.Navigation("CoffeeBags");
                });
#pragma warning restore 612, 618
        }
    }
}
