// <auto-generated />
using System;
using Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Api.Database.Entities.Brew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrewType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CoffeeBagId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CoffeeDose")
                        .HasColumnType("REAL");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<double?>("GrindSize")
                        .HasColumnType("REAL");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutputAddedTasteScore")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("OutputAddedWeight")
                        .HasColumnType("REAL");

                    b.Property<int?>("OutputTasteScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OutputTime")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("OutputWeight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeBagId");

                    b.ToTable("Brews");
                });

            modelBuilder.Entity("Api.Database.Entities.CoffeeBag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Emptied")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavourNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Opened")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoastStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Roaster")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CoffeeBags");
                });

            modelBuilder.Entity("Api.Database.Entities.Brew", b =>
                {
                    b.HasOne("Api.Database.Entities.CoffeeBag", "CoffeeBag")
                        .WithMany()
                        .HasForeignKey("CoffeeBagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoffeeBag");
                });
#pragma warning restore 612, 618
        }
    }
}
